<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class BuildPsychiatristAssets extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'psych:build';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Concatenate the psychiatrist JS module fragments into public/js/psych/psychiatrist.js';

    /**
     * Module fragment files, in the exact order they must be concatenated.
     * They share state via top-level var/function declarations inside one
     * shared DOMContentLoaded closure opened by *_core.js and closed by
     * *_init.js.
     *
     * @var array<int, string>
     */
    protected array $modules = [
        'psychiatrist_core.js',
        'psychiatrist_patients.js',
        'psychiatrist_consultations.js',
        'psychiatrist_assessments.js',
        'psychiatrist_lifestyle.js',
        'psychiatrist_prescriptions.js',
        'psychiatrist_init.js',
    ];

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $dir = public_path('js/psych');
        $target = $dir . DIRECTORY_SEPARATOR . 'psychiatrist.js';

        $parts = [];

        foreach ($this->modules as $file) {
            $path = $dir . DIRECTORY_SEPARATOR . $file;

            if (!is_file($path)) {
                $this->error("Missing module file: {$path}");
                $this->error('All psychiatrist module fragments must exist before building. Aborting — the existing psychiatrist.js was NOT overwritten.');

                return self::FAILURE;
            }

            $contents = file_get_contents($path);

            if ($contents === false) {
                $this->error("Unable to read module file: {$path}");

                return self::FAILURE;
            }

            $parts[] = "/* ===== {$file} ===== */\n" . rtrim($contents) . "\n";
        }

        $banner = <<<'BANNER'
/*
 * DO NOT EDIT — generated by `php artisan psych:build`.
 *
 * This file is built by concatenating the module fragments in
 * public/js/psych/psychiatrist_*.js. To make changes, edit the module
 * files and re-run `php artisan psych:build`.
 */

BANNER;

        $output = $banner . "\n" . implode("\n", $parts);

        if (file_put_contents($target, $output) === false) {
            $this->error("Unable to write output file: {$target}");

            return self::FAILURE;
        }

        $this->info('Built ' . $target);
        $this->line('Modules concatenated in order:');
        foreach ($this->modules as $file) {
            $this->line('  - ' . $file);
        }

        return self::SUCCESS;
    }
}
