<?php

/*
 * Safeguards for the generated psychiatrist asset bundle.
 *
 * public/js/psych/psychiatrist.js is GENERATED by `php artisan psych:build`
 * by concatenating the module fragments public/js/psych/psychiatrist_*.js
 * (they are unwrapped closure fragments and must NEVER be loaded as
 * standalone <script> tags — the only file served to the browser is the
 * built output under the same filename).
 *
 * These tests fail if the build is missing, stale, or drifts from the
 * expected module content, so a forgotten rebuild can't silently ship.
 */

const MODULES = [
    'psychiatrist_core.js',
    'psychiatrist_patients.js',
    'psychiatrist_consultations.js',
    'psychiatrist_assessments.js',
    'psychiatrist_lifestyle.js',
    'psychiatrist_prescriptions.js',
    'psychiatrist_init.js',
];

function psychBuildPath(): string
{
    return public_path('js/psych/psychiatrist.js');
}

function psychModulePaths(): array
{
    return array_map(fn (string $f) => public_path('js/psych/' . $f), MODULES);
}

test('built psychiatrist.js exists', function () {
    expect(file_exists(psychBuildPath()))->toBeTrue();
});

test('built psychiatrist.js is not stale (newer than every module fragment)', function () {
    $builtMtime = filemtime(psychBuildPath());

    foreach (psychModulePaths() as $path) {
        expect(file_exists($path))->toBeTrue(
            'Missing module file: ' . basename($path)
        );

        expect($builtMtime)->toBeGreaterThanOrEqual(
            filemtime($path),
            basename($path) . ' is newer than the built psychiatrist.js — run `php artisan psych:build`.'
        );
    }
});

test('built psychiatrist.js contains all module fragments in order', function () {
    $src = file_get_contents(psychBuildPath());

    $offset = 0;
    foreach (MODULES as $module) {
        $marker = '/* ===== ' . $module . ' ===== */';
        $found = strpos($src, $marker, $offset);
        expect($found)->not->toBeFalse("Missing or out-of-order marker for {$module}");
        $offset = $found;
    }

    expect(str_starts_with($src, '/*'))->toBeTrue('Generated banner comment missing');
    expect($src)->toContain('DO NOT EDIT');
});

test('built psychiatrist.js print functions use the preview modal, never window.open', function () {
    $src = file_get_contents(psychBuildPath());

    expect($src)->not->toMatch('/window\.open\s*\(/', 'window.open() popup found in the built bundle');
    expect($src)->toContain('function showPrintPreview(');
    expect($src)->toContain("openModal(\"rx-print-modal\")");
    expect($src)->toContain('window.printRx');
    expect($src)->toContain('window.printDx');
});

test('built psychiatrist.js is a valid script (balanced closure opened by core, closed by init)', function () {
    $src = file_get_contents(psychBuildPath());

    // core.js opens the shared DOMContentLoaded closure; init.js must close it.
    $corePos = strpos($src, "document.addEventListener('DOMContentLoaded'");
    expect($corePos)->not->toBeFalse();
    expect(trim($src))->toEndWith('});');
});
